development:
  adapter: postgresql
  encoding: utf8
  database: cinco_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: cinco_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: cinco_production
  pool: 5
  username:
  password:
